# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("greet.proto", :syntax => :proto3) do
    add_message "test.HelloRequest" do
      optional :name, :string, 1
    end
    add_message "test.HelloReply" do
      optional :message, :string, 1
    end
    add_message "test.HiRequest" do
      optional :car, :string, 1
    end
    add_message "test.HiReply" do
      optional :message, :string, 1
    end
    add_message "test.NumRequest" do
      optional :message, :float, 1
    end
    add_message "test.NumberResponse" do
      optional :message, :float, 1
    end
  end
end

module Test
  HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test.HelloRequest").msgclass
  HelloReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test.HelloReply").msgclass
  HiRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test.HiRequest").msgclass
  HiReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test.HiReply").msgclass
  NumRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test.NumRequest").msgclass
  NumberResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test.NumberResponse").msgclass
end
